#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master
    
before_script:
  - npm install -g webpack webpack-dev-server typescript
  - npm install  
script:
  - webpack --progress

notifications:
  email:
    on_failure: change
    on_success: change
